name: "Compile scss"

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      
      - name: Install sass
        run: npm install -g sass
      
      - name: Compile all SCSS
        run: |
          shopt -s globstar
          for f in styles/**/*.scss; do
            if [[ $(basename "$f") != _* ]]; then
              sass "$f" "${f%.scss}.css" --style=compressed
            fi
          done
      
      - name: Commit and push compiled scss
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add styles/*.css
          git commit -m "GitHub Actions: compile scss" || echo "No changes to commit"
          git push